export { default as TeacherAdminLayout } from './Layout';
export { default as TeacherAdminHeader } from './Header';
export { default as TeacherAdminSidebar } from './Sidebar';
export { default as TeacherAdminDashboard } from './TeacherAdminDashboard';
export { default as DashboardContent } from './Dashboard/DashboardContent';
export { TeacherProfile, EditProfileModal } from './Profile';
export { Students } from './Students';
export { StudentResult } from './Results';
export { ExamTimetable } from './ExamTimetable';
export { Events } from './Events';
export { TeacherAnnouncements } from './Announcements';
export { StudentAttendance, YourAttendance } from './Attendance';
export { TeacherLeave } from './Leave';
export { Homework } from './Homework';
