// API Configuration
export const API_CONFIG = {
  BASE_URL: 'http://localhost:5000/api',
  ENDPOINTS: {
    AUTH: {
      LOGIN: '/auth/login',
      LOGOUT: '/auth/logout',
      REFRESH: '/auth/refresh',
      FORGOT_PASSWORD: '/auth/forgot-password',
      RESET_PASSWORD: '/auth/reset-password',
    },
    SCHOOL: {
      PROFILE: '/school/profile',
      UPDATE_PROFILE: '/school/profile',
      DASHBOARD: '/school/dashboard',
      DETAILS: '/schools/:schoolId/details',
      GET_PROFILE: '/schools/:schoolId/',
      UPDATE_PROFILE_BY_ID: '/schools/:schoolId/profile',
    },
    STUDENTS: {
      LIST: '/students',
      CREATE: '/students',
      UPDATE: '/students/:studentId',
      DELETE: '/students/:studentId',
      DETAILS: '/students/:studentId',
      BY_SCHOOL: '/students/school/:schoolId',
    },
    TEACHERS: {
      LIST: '/teachers',
      CREATE: '/teachers',
      UPDATE: '/teachers/:id',
      UPDATE_BY_ID: '/teachers/update/:id',
      DELETE: '/teachers/:id',
      DELETE_BY_ID: '/teachers/delete/:id',
      DETAILS: '/teachers/:id',
      BY_SCHOOL: '/teachers/school/:schoolId',
      ADD: '/teachers',
      EDIT: '/teachers/:teacherId',
      DELETE_TEACHER: '/teachers/:teacherId',
    },
    TEACHER_ATTENDANCE: {
      MARK: '/teacher-attendance/',
      GET_BY_DATE: '/teacher-attendance/:schoolId/date/:date',
      GET_MARKED_DATES: '/teacher-attendance/:schoolId/dates',
      DOWNLOAD_REPORT: '/teacher-attendance/teacher/download-report',
      SUMMARY: '/teacher-attendance/teacher/summary',
      GET_STATUS: '/teacher-attendance/teacher/:schoolId/:date/:teacherId',
      BULK_MARK: '/teacher-attendance/',
    },
    CLASSROOM: {
      GET_CLASSES: '/classrooms/:schoolId/academicYears/:yearId/classes',
      CREATE_CLASS: '/classrooms/:schoolId/academicYears/:yearId/classes',
      UPDATE_CLASS: '/classrooms/:schoolId/academicYears/:yearId/classes/:classId',
      DELETE_CLASS: '/classrooms/:schoolId/academicYears/:yearId/classes/:classId',
    },
    ATTENDANCE: {
      LIST: '/attendance',
      MARK: '/attendance/mark',
      REPORT: '/attendance/report',
    },
    EXAMS: {
      LIST: '/exams',
      CREATE: '/exams',
      UPDATE: '/exams/:id',
      DELETE: '/exams/:id',
      TIMETABLE: '/exams/timetable',
      // New Exam Timetable endpoints with school and academic year
      GET_TIMETABLES: '/exam-timetables/:schoolId/:yearId/examTimetable',
      GET_TIMETABLE: '/exam-timetables/:schoolId/:yearId/examTimetable/:timetableId',
      CREATE_TIMETABLE: '/exam-timetables/:schoolId/:yearId/examTimetable',
      UPDATE_TIMETABLE: '/exam-timetables/:schoolId/:yearId/examTimetable/:timetableId',
      DELETE_TIMETABLE: '/exam-timetables/:schoolId/:yearId/examTimetable/:timetableId',
      DELETE_SUBJECT: '/exam-timetables/:schoolId/:yearId/examTimetable/:timetableId/subject/:subjectId',
    },
    STUDENT_PAYMENTS: {
      SUMMARY_BY_SCHOOL: '/student-payments/school/:schoolId/:yearId/summary',
      DOWNLOAD_CLASS_REPORT: '/student-payments/reports/class-wise',
      DOWNLOAD_STUDENT_REPORT: '/student-payments/reports/student-receipt',
      ADD_PAYMENT: '/student-payments/:schoolId/:yearId/payments',
      GET_STUDENT_PAYMENTS: '/student-payments/:schoolId/:yearId/students/:studentId',
      DELETE_PAYMENTS: '/student-payments/:schoolId/:yearId/students/:studentId/payments',
      UPDATE_PAYMENT: '/student-payments/:schoolId/:yearId/students/:studentId/payments/:paymentId',
      GET_PAYMENT: '/student-payments/:schoolId/:yearId/students/:studentId/payments/:paymentId',
      ALL_SCHOOL_PAYMENTS: '/student-payments/school/:schoolId/all-payments',
      STATISTICS: '/student-payments/school/:schoolId/:yearId/statistics',
    },
    ANNOUNCEMENTS: {
      GET_BY_SCHOOL: '/announcements/:schoolId/announcements',
      CREATE_ANNOUNCEMENT: '/announcements/:schoolId/announcements',
      UPDATE_ANNOUNCEMENT: '/announcements/:schoolId/announcements/:announcementId',
      DELETE_ANNOUNCEMENT: '/announcements/:schoolId/announcements/:announcementId',
    },
    SUBSCRIPTIONS: {
      GET_BY_SCHOOL: '/subscriptions/school/:schoolId',
      CREATE: '/subscriptions/',
      GET_COST: '/subscriptions/subscription-cost',
      DOWNLOAD_INVOICE: '/subscriptions/download-invoice',
    },
    PAYMENT_GATEWAY: {
      RAZORPAY: {
        CREATE_ORDER: '/payment-gateway/razorpay/create-order',
        VERIFY_PAYMENT: '/payment-gateway/razorpay/verify-payment',
      },
    },
    FEES: {
      LIST: '/fees',
      CREATE: '/fees',
      UPDATE: '/fees/:id',
      DELETE: '/fees/:id',
      PAYMENT: '/fees/payment',
    },
    EVENTS: {
      CREATE: '/events/:schoolId/events',
      GET_ALL: '/events/events/:schoolId',
      GET_BY_ID: '/events/events/:schoolId/:eventId',
      UPDATE: '/events/:schoolId/events/:eventId',
      DELETE: '/events/events/:schoolId/:eventId',
      DELETE_MULTIPLE: '/events/delete-multiple/:schoolId',
    },
  },
}; 